#! /bin/bash

SCRIPT_DIR=`dirname $0`
source ${SCRIPT_DIR}/common-functions
exit_if_no_arguments $#

FILE=${1}

if [ ! -f ${FILE} ]; then
	echo File ${FILE} does not exist!
	exit 1
fi

FILE_NO_EXT=${FILE%.*}

FO_FILE=${FILE_NO_EXT}.fo
PDF_FILE=${FILE_NO_EXT}.pdf

xsltproc /usr/share/xml/docbook/stylesheet/docbook-xsl-ns/fo/docbook.xsl ${FILE} > ${FO_FILE}
fop -fo ${FO_FILE} -pdf ${PDF_FILE}
