#! /bin/bash

SCRIPT_DIR=`dirname $0`
source ${SCRIPT_DIR}/common-functions

exit_if_no_arguments $#
exit_if_file_does_not_exist $1

FILE_NO_EXT=${FILE%.*}
HTML_FILE=${FILE_NO_EXT}.html

xsltproc /usr/share/xml/docbook/stylesheet/docbook-xsl-ns/html/docbook.xsl ${FILE} > ${HTML_FILE}
