#! /bin/bash

# Import common functions
SCRIPT_DIR=`dirname $0`
source ${SCRIPT_DIR}/common-functions

# Validate input
exit_if_no_arguments $#
INPUT_FILE=$1
exit_if_file_does_not_exist $INPUT_FILE

# Prepare file names
FILE_NO_EXT=${INPUT_FILE%.*}
FO_FILE=${FILE_NO_EXT}.fo
PDF_FILE=${FILE_NO_EXT}.pdf

# Generate
log "Generating PDF from $INPUT_FILE"
xsltproc /usr/share/xml/docbook/stylesheet/docbook-xsl-ns/fo/docbook.xsl $INPUT_FILE > $FO_FILE
fop -fo $FO_FILE -pdf $PDF_FILE
