#! /bin/bash

ARG_COUNT=$#

if [[ ${ARG_COUNT} -eq 0 ]]; then
	echo File name not specified!
	exit 1
fi

FILE=${1}

if [ ! -f ${FILE} ]; then
	echo File ${FILE} does not exist!
	exit 1
fi

FILE_NO_EXT=${FILE%.*}
HTML_FILE=${FILE_NO_EXT}.html

xsltproc /usr/share/xml/docbook/stylesheet/docbook-xsl-ns/html/docbook.xsl ${FILE} > ${HTML_FILE}
