#! /bin/bash

ARG_COUNT=$#

if [[ ${ARG_COUNT} -eq 0 ]]; then
	echo File name not specified!
	exit 1
fi

FILE=${1}

if [ ! -f ${FILE} ]; then
	echo File ${FILE} does not exist!
	exit 1
fi

xmlstarlet val --err --xsd /usr/share/xml/docbook/schema/xsd/5.0/docbook.xsd ${FILE}
