#! /bin/bash

SCRIPT_DIR=`dirname $0`
source ${SCRIPT_DIR}/common-functions

exit_if_no_arguments $#
exit_if_file_does_not_exist $1

xmlstarlet val --err --xsd /usr/share/xml/docbook/schema/xsd/5.0/docbook.xsd ${FILE}
